version: "3.9"
services:
  strapi:
    image: strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - '1337:1337'
    depends_on:
      - db