version: "3.9"
services:
  strapi:
    image: strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=postgres
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - URL=http://localhost:1337
      - FRONTEND_URL=http://localhost:3006
      - DOMAIN=localhost
      - AUDIT_FREQ_MINUTES=2
      - STRAPI_LOG_LEVEL=debug
    ports:
      - '1337:1337'
    depends_on:
      - db
    volumes:
      - ../strapi:/srv/app
      # Map empty volume so docker doesn't use node_modules from host
      - /srv/app/node_modules/