version: "3.9"
services:
  discord-bot:
    image: discord-bot
    entrypoint: ["npm", "run", "docker-start"]
    environment:
      - PORT=3000
      - BACKEND_MTLS_CERT=./dev/cert.pem
      - BACKEND_MTLS_KEY=./dev/key.key
      - DISCORD_BOT_POSTGRES_USER=postgres
      - DISCORD_BOT_POSTGRES_PASSWORD=postgres
      - DISCORD_BOT_POSTGRES_DB=postgres
      - DISCORD_BOT_POSTGRES_HOST=db
      - DISCORD_BOT_POSTGRES_PORT=5432
    depends_on:
      - db
      - discord-bot-migrations
  discord-bot-migrations:
    image: discord-bot-migrations
    environment:
      - DISCORD_BOT_POSTGRES_USER=postgres
      - DISCORD_BOT_POSTGRES_PASSWORD=postgres
      - DISCORD_BOT_POSTGRES_DB=postgres
      - DISCORD_BOT_POSTGRES_HOST=db
      - DISCORD_BOT_POSTGRES_PORT=5432
    depends_on:
      - db
